export type WorkShift = {
  id: string;
  code: string;
  name: string;
  startTime: string;
  endTime: string;
  breakStartTime?: string | null;
  breakEndTime?: string | null;
  lateGracePeriod?: number | null;
  earlyLeaveGracePeriod?: number | null;
  checkInStartTime?: string | null;
  checkInEndTime?: string | null;
  checkOutStartTime?: string | null;
  checkOutEndTime?: string | null;
  isOvertime: boolean;
  workUnits: number | string;
  overtimeMultiplier?: number | string | null;
  isActive?: boolean;
  createdAt?: string;
  updatedAt?: string;
};

export type WorkShiftFormPayload = {
  code: string;
  name: string;
  startTime: string;
  endTime: string;
  breakStartTime?: string;
  breakEndTime?: string;
  lateGracePeriod?: number;
  earlyLeaveGracePeriod?: number;
  checkInStartTime?: string;
  checkInEndTime?: string;
  checkOutStartTime?: string;
  checkOutEndTime?: string;
  isOvertime?: boolean;
  workUnits: number;
  overtimeMultiplier?: number;
  isActive?: boolean;
};
